# Generated by Django 4.2.18 on 2025-01-25 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название блюда')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Стоимость блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Номер стола не может быть отрицательным')], verbose_name='Номер столика')),
                ('total_price', models.PositiveIntegerField(verbose_name='Общая стоимость заказа')),
                ('status', models.CharField(choices=[('waiting', 'в ожидании'), ('ready', 'готово'), ('paid', 'оплачено')], max_length=256, verbose_name='Статус заказа')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.item', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
