# Generated by Django 4.2.18 on 2025-01-25 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'в ожидании'), ('ready', 'готово'), ('paid', 'оплачено')], max_length=255, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Номер столика не может быть отрицательным')], verbose_name='Номер столика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Общая стоимость заказа не может быть отрицательной')], verbose_name='Общая стоимость заказа'),
        ),
    ]
