# Generated by Django 4.2.18 on 2025-01-25 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_item_title_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Общая стоимость заказа не может быть отрицательной')], verbose_name='Общая стоимость заказа'),
        ),
    ]
